### ISSUE TITLE
Butler needs a face

### ISSUE THREAD

**Issue by keathley** [ButlerBot/butler#11]
Butler needs a persona. Anyone wanna try their hand at some illustration work?

**Comment by colinrymer** [comment]
![untitled drawing](https://cloud.githubusercontent.com/assets/724007/9950191/dee83f7a-5d85-11e5-8c16-2830e710db5c.png)

**Comment by brettwise** [comment]
Love this.

**Comment by colinrymer** [comment]
The image I posted seems to have overwhelming support compared to the alternatives. :trollface:

**Comment by bbrock25** [comment]
:tophat:

**Comment by bbrock25** [comment]
working with a designer at spartan on this, do we have any logos of other projects that we like that could give him some direction? @keathley @colinrymer

**Comment by colinrymer** [comment]
Not sure how he could improve on the above...

**Comment by keathley** [comment]
@bbrock25 hubot

**Comment by brettwise** [comment]
Yeah Colin already did an amazing job. Why redo what's been done?
