### ISSUE TITLE
Respond to more slack messages

### ISSUE THREAD

**Issue by keathley** [ButlerBot/butler#15]
There a several slack messages that we don't currently respond to. The full list is here: https://api.slack.com/rtm. Here's what I can think of off the top of my head:
- [ ] `hello`
- [ ] `channel_created`
- [ ] `channel_joined`
- [ ] `channel_left`
- [ ] `channel_rename`
- [ ] `channel_archive`
- [ ] `channel_unarchive`
- [ ] `group_joined`
- [ ] `group_left`
- [ ] `group_rename`
- [ ] `group_archive`
- [ ] `group_unarchive`
- [ ] `team_rename`
- [ ] `team_join`
- [ ] `user_change`
- [ ] `bot_added`
- [ ] `bot_changed`

We can use each of these to update the adapter about the state of slack.

**Comment by bbrock25** [comment]
yay +1

**Comment by keathley** [comment]
@bbrock25 Most of these don't actually need to propagate out to the plugins (although some of them like users joining channels could be interesting). I can think of a lot of cool plugins we could build if we had access to that state though.

**Comment by bbrock25** [comment]
That's what I was wondering, since those are events and not really specific messages.
