### ISSUE TITLE
Add history to the console adapter

### ISSUE THREAD

**Issue by keathley** [ButlerBot/butler#16]
It would be really convenient to have history in the console adapter like in a standard repl or terminal. This will probably involve writing directly to tty or something similar in order to capture the up arrow and down arrow keys.

**Comment by bbrock25** [comment]
Been thinking about this one as a fun feature to implement, I wonder if it would make sense to use [ETS](http://elixir-lang.org/getting-started/mix-otp/ets.html) to manage the state?

**Comment by keathley** [comment]
I was thinking of just using an Agent. What were your thoughts about using ETS?

**Comment by bbrock25** [comment]
I wasn't aware of Agent, will take a look.
