### ISSUE TITLE
Butler.Adapter.Console isn't capturing tty output

### ISSUE THREAD

**Issue by bbrock25** [ButlerBot/butler#18]
Not sure what happened in the most recent commits, but for some reason, when I run 

```
iex -S mix
```

I get the following output: 

```
bbrock:butler/ (feature-docs✗) $ iex -S mix                                              [12:56:36]
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiled lib/butler/adapters/slack/rtm.ex
Compiled lib/butler.ex
Compiled lib/butler/supervisor.ex
Compiled lib/butler/plugin.ex
Compiled lib/butler/adapters/console.ex
Compiled lib/butler/message.ex
Compiled lib/butler/bot.ex
Compiled lib/butler/adapters/slack.ex
Compiled lib/butler/plugins/cowsay.ex
Compiled lib/butler/plugins/test_count.ex
Generated butler app
butler>Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

It seems that the iex repl is taking back over and dropping the `butler>` prompt. I'll dig into it, but wasn't sure if it was something simple that I missed. 

Butler.Adapter.Slack is still functional

**Comment by keathley** [comment]
This is somewhat expected. The process that runs the Butler repl is started but mix won't block while it waits for input. So it drops you back into iex. If you want to run the Butler repl you need to run `mix run --no-halt` instead.

**Comment by keathley** [comment]
I've updated the README to use the correct command.

**Comment by bbrock25** [comment]
Awesome, thanks!
