### ISSUE TITLE
Installation command in README.md does not work

### ISSUE THREAD

**Issue by dfederschmidt** [ButlerBot/butler#36]
The Readme suggests to install the butler archive with the following command:

```
mix archive.install https://github.com/butlerbot/butler/releases/download/v0.7.1/butler_new-0.7.1.ez
```

The command fails because `butler_new-0.7.1.ez` does not exist which becomes clear on the Releases page of the repository: https://github.com/keathley/butler/releases

As 0.7.1 seems to be just documentation I just downloaded 0.7.0 as a workaround but I still wanted to open an issue on that matter.

**Comment by keathley** [comment]
Thanks for opening this. I need to update all of the documentation anyway. We're actually in the process of deprecating Butler and merging a lot of its functionality into hedwig-im/hedwig. I'll update the README so that its clear for people. Sorry about the confusion.
